### PR TITLE
Update chrome::/extension link

### PR DESCRIPTION
**Pull request by xyzqm**

### CODE REVIEW

**Comment by goombamaui** [comment]
I believe the link is `chrome://extensions`. Can you please confirm.

**Comment by gadhagod** [comment]
Yes, the link is [chrome://extensions](chrome://extensions).

**Comment by xyzqm** [comment]
Ah yeah, chrome://extensions.
It was chrome:extensions earlier.

**Comment by gadhagod** [comment]
Thanks for mentioning this. I've just commited the fix.

**Pull request closed without merging**
