### PR TITLE
Add download counter

### PR DESCRIPTION
**Pull request by gadhagod**

### CODE REVIEW

**Review by goombamaui — CHANGES_REQUESTED** [review]
Move code to seperate repo.

**Comment by gadhagod** [comment]
TODO: rate limiting

**Review by goombamaui — DISMISSED** [review]

**Comment by gadhagod** [comment]
TODO: Rate limiting

**Comment by gadhagod** [comment]
@goombamaui how is 30 requests per day as a rate limit?

**Review by goombamaui — APPROVED** [review]

**Pull request merged**
